name: Delete all files in repo

on:
  workflow_dispatch:  # Cho phép chạy thủ công

permissions:
  contents: write

jobs:
  delete-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete all files
        run: |
          git rm -r --cached .    # Xóa file khỏi index
          find . -mindepth 1 -not -path "./.git*" -exec rm -rf {} +  # Xóa tất cả ngoại trừ .git

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Delete all files"
          git push
